### ISSUE TITLE
Some dependencies are no longer available in Ubuntu 14.10. 

### ISSUE THREAD

**Issue by v6** [tmakkonen/sipcmd#38]
// , 

➜  sipcmd git:(master) sudo apt-get install opal-dev ptlib-dev 
[sudo] password for v6: 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Unable to locate package opal-dev
E: Unable to locate package ptlib-dev

**Comment by frixhub** [comment]
Good day,

I'm running Kubuntu 14.04. What worked for me was:
$ sudo apt-get install libopal-dev libpt-dev

Regards,
Frix

**Comment by v6** [comment]
// , Should we fix the documentation, or something?

**Comment by mikhailnov** [comment]
Yes, you shuld fizz the ocumentation, this also works for Ubuntu 16.04 LTS

**Comment by tmakkonen** [comment]
Docs fixed.
