### ISSUE TITLE
Video possible

### ISSUE THREAD

**Issue by pergolafabio** [tmakkonen/sipcmd#78]
Hi @tmakkonen , just found this project, is it also possible to start a call with video? maybe with a /dev/videoX device?
Would be usefull in combination with a v4l2-loopback

thnx

**Comment by soroshsabz** [comment]
@pergolafabio Did you can provide some PR for it?

thanks

**Comment by pergolafabio** [comment]
Hi, no, dont have that knowledge , i use now baresip console client, it can use an rtsp or v4l2 as source
